// src/data/gloves.js 由 Fable-3 产出。它缺席时用这份占位表，字段与契约一致，
// 数值只求「手感能跑通」，正式平衡以 data 模块为准。

export const MATCH = {
  dt: 1 / 60,
  arenaRadius: 20,
  playerRadius: 0.7,
  playerHeight: 2,
  fallY: -8,
  respawnDelay: 1.2,
  invulnTime: 1.0,
  matchSeconds: 240,
  killsToWin: 7,
  switchLock: 0.4,
  awakenDuration: 8,
};

export const GLOVES = [
  {
    id: "cotton",
    name: "木棉",
    role: "教学",
    material: "浆洗过头的粗棉布，指节处磨出毛边",
    color: "#cbb9a0",
    slapRange: 2.6,
    slapAngleDeg: 95,
    slapPower: 8.5,
    slapCooldown: 0.42,
    windup: 0.08,
    recovery: 0.16,
    skillId: "none",
    skillName: "无",
    skillCooldown: 0,
    skillDesc: "没有主动技。它只是扇得比谁都快。",
    awakenDesc: "第 3 下附带强击退",
    unlock: { type: "default", text: "初始携带", req: {} },
  },
  {
    id: "granite",
    name: "磐石",
    role: "重击",
    material: "铸铁护片压在旧牛皮上，边角磕出白茬",
    color: "#8d8b83",
    slapRange: 2.9,
    slapAngleDeg: 70,
    slapPower: 15,
    slapCooldown: 0.85,
    windup: 0.22,
    recovery: 0.34,
    skillId: "quake",
    skillName: "砸地",
    skillCooldown: 7,
    skillDesc: "蓄力砸地，小范围击飞，台面留裂。",
    awakenDesc: "砸击直接裂开台面子块",
    unlock: { type: "challenge", text: "一局内把 2 人扇出岛", req: { kills: 2 } },
  },
  {
    id: "gale",
    name: "疾风",
    role: "切入",
    material: "薄麻缠指，掌心一层被风磨亮的漆",
    color: "#7fb3a8",
    slapRange: 2.5,
    slapAngleDeg: 85,
    slapPower: 9.5,
    slapCooldown: 0.5,
    windup: 0.07,
    recovery: 0.18,
    skillId: "rush",
    skillName: "贯风",
    skillCooldown: 5,
    skillDesc: "面向冲刺，途中可以继续扇。",
    awakenDesc: "冲刺中可以转向一次",
    unlock: { type: "challenge", text: "一局内冲刺 5 次并至少 1 杀", req: { dashes: 5, kills: 1 } },
  },
  {
    id: "frost",
    name: "冰霜",
    role: "控制",
    material: "结霜的鞣皮，缝线里嵌着化不掉的白",
    color: "#9dc4d8",
    slapRange: 2.7,
    slapAngleDeg: 110,
    slapPower: 7,
    slapCooldown: 0.6,
    windup: 0.12,
    recovery: 0.2,
    skillId: "frostArc",
    skillName: "霜弧",
    skillCooldown: 6,
    skillDesc: "扫出一道霜弧，命中者减速。",
    awakenDesc: "霜弧改为冻结 0.8 秒",
    unlock: { type: "challenge", text: "一局内 3 杀", req: { kills: 3 } },
  },
  {
    id: "spring",
    name: "弹簧",
    role: "反制",
    material: "钢丝盘成掌骨，外面裹一层旧橡胶",
    color: "#b6a15e",
    slapRange: 2.4,
    slapAngleDeg: 90,
    slapPower: 8,
    slapCooldown: 0.55,
    windup: 0.1,
    recovery: 0.2,
    skillId: "parry",
    skillName: "反弹",
    skillCooldown: 6.5,
    skillDesc: "0.5 秒架势，期间挨打把对方弹回去。",
    awakenDesc: "弹回附带一次小跳",
    unlock: { type: "challenge", text: "一局内 3 杀且一次没掉下去", req: { kills: 3, noDeaths: true } },
  },
  {
    id: "afterimage",
    name: "分身",
    role: "欺诈",
    material: "半透的绸面手套，掌纹像被水洗淡了",
    color: "#a08fc0",
    slapRange: 2.5,
    slapAngleDeg: 80,
    slapPower: 8.5,
    slapCooldown: 0.5,
    windup: 0.09,
    recovery: 0.18,
    skillId: "blink",
    skillName: "残影",
    skillCooldown: 8,
    skillDesc: "留下残影并短距换位。",
    awakenDesc: "残影会替你假挥一掌",
    unlock: { type: "challenge", text: "从背后扇出 3 次击杀", req: { behindKills: 3 } },
  },
  {
    id: "magnet",
    name: "磁掌",
    role: "强制接近",
    material: "缠着铜线的皮掌，指尖吸着一层铁屑",
    color: "#c07a58",
    slapRange: 2.6,
    slapAngleDeg: 75,
    slapPower: 9,
    slapCooldown: 0.6,
    windup: 0.12,
    recovery: 0.22,
    skillId: "pull",
    skillName: "牵引",
    skillCooldown: 7,
    skillDesc: "把面前 1 人拉到身前。",
    awakenDesc: "可以同时拉 2 人并短暂黏住",
    unlock: { type: "challenge", text: "一局内 5 杀", req: { kills: 5 } },
  },
  {
    id: "meteor",
    name: "陨掌",
    role: "清场",
    material: "烧结过的黑石护甲，缝隙里还留着灰",
    color: "#d08a45",
    slapRange: 3.0,
    slapAngleDeg: 70,
    slapPower: 13,
    slapCooldown: 0.9,
    windup: 0.24,
    recovery: 0.36,
    skillId: "meteorFall",
    skillName: "坠掌",
    skillCooldown: 11,
    skillDesc: "自己腾空，随后高空砸下。",
    awakenDesc: "落地裂开周围一圈台面",
    unlock: { type: "challenge", text: "单局达成 7 杀", req: { kills: 7 } },
  },
];

export const GLOVE_BY_ID = Object.fromEntries(GLOVES.map((g) => [g.id, g]));

export const BOT_NAMES = ["莽夫", "狐步", "拾荒"];
export const BOT_PERSONAS = ["brute", "fox", "bully"];
