// sim 内置兜底数据表。
// TODO(merge): `src/data/gloves.js` 落地后，deps.js 会自动改用真实 MATCH / GLOVES，
// 本文件只作为“data 还没合进来”时的占位，勿在此长期维护数值。

/** 与 CONTRACT.md 一致的对局常量 */
export const MATCH = {
  dt: 1 / 60,
  arenaRadius: 20,
  playerRadius: 0.7,
  playerHeight: 2,
  fallY: -8,
  respawnDelay: 1.2,
  invulnTime: 1.0,
  matchSeconds: 240,
  killsToWin: 7,
  switchLock: 0.4,
  awakenDuration: 8,
};

/**
 * 手套字段最低集：
 * id, name, role, color, slapRange, slapAngleDeg, slapPower,
 * slapCooldown, windup, recovery, skillId, skillCooldown, unlock
 * 只有 cotton（木棉）是按 Round 1 竖切调过的；其余标 placeholder，等 data 覆盖。
 */
export const GLOVES = [
  {
    id: "cotton",
    name: "木棉",
    role: "starter",
    color: "#e6d9bd",
    slapRange: 2.7,
    slapAngleDeg: 100,
    slapPower: 9,
    slapCooldown: 0.42,
    windup: 0.09,
    recovery: 0.16,
    skillId: null,
    skillCooldown: 0,
    unlock: "default",
    placeholder: false,
  },
  {
    id: "granite",
    name: "磐石",
    role: "heavy",
    color: "#8d8a83",
    slapRange: 3.0,
    slapAngleDeg: 80,
    slapPower: 15,
    slapCooldown: 0.85,
    windup: 0.22,
    recovery: 0.34,
    skillId: "granite-quake",
    skillCooldown: 9,
    unlock: "challenge",
    placeholder: true,
  },
  {
    id: "gale",
    name: "疾风",
    role: "rush",
    color: "#9fc6c0",
    slapRange: 2.6,
    slapAngleDeg: 90,
    slapPower: 7.5,
    slapCooldown: 0.34,
    windup: 0.07,
    recovery: 0.12,
    skillId: "gale-dash",
    skillCooldown: 6,
    unlock: "challenge",
    placeholder: true,
  },
  {
    id: "frost",
    name: "冰霜",
    role: "control",
    color: "#a8c4de",
    slapRange: 2.9,
    slapAngleDeg: 110,
    slapPower: 7,
    slapCooldown: 0.5,
    windup: 0.12,
    recovery: 0.2,
    skillId: "frost-arc",
    skillCooldown: 7,
    unlock: "challenge",
    placeholder: true,
  },
  {
    id: "spring",
    name: "弹簧",
    role: "counter",
    color: "#c8b25f",
    slapRange: 2.5,
    slapAngleDeg: 95,
    slapPower: 8,
    slapCooldown: 0.5,
    windup: 0.1,
    recovery: 0.18,
    skillId: "spring-guard",
    skillCooldown: 8,
    unlock: "challenge",
    placeholder: true,
  },
  {
    id: "afterimage",
    name: "分身",
    role: "trick",
    color: "#b0a6c9",
    slapRange: 2.6,
    slapAngleDeg: 85,
    slapPower: 8.5,
    slapCooldown: 0.45,
    windup: 0.1,
    recovery: 0.16,
    skillId: "afterimage-swap",
    skillCooldown: 10,
    unlock: "challenge",
    placeholder: true,
  },
  {
    id: "magnet",
    name: "磁掌",
    role: "pull",
    color: "#a5675a",
    slapRange: 3.2,
    slapAngleDeg: 75,
    slapPower: 6.5,
    slapCooldown: 0.55,
    windup: 0.14,
    recovery: 0.22,
    skillId: "magnet-pull",
    skillCooldown: 9,
    unlock: "challenge",
    placeholder: true,
  },
  {
    id: "meteor",
    name: "陨掌",
    role: "nuke",
    color: "#c2743d",
    slapRange: 3.1,
    slapAngleDeg: 90,
    slapPower: 13,
    slapCooldown: 0.8,
    windup: 0.25,
    recovery: 0.38,
    skillId: "meteor-drop",
    skillCooldown: 14,
    unlock: "challenge",
    placeholder: true,
  },
];

export const GLOVE_BY_ID = Object.fromEntries(GLOVES.map((g) => [g.id, g]));
